name: Issue Comment
on:
  issue_comment:
    types: [ created ]

permissions:
  pull-requests: read
  contents: read
jobs:
  pr_details:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'test comment')
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "This was triggered for $COMMENT_BODY"
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
