# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
  push:
    tags:       
      - v1.*
  issue_comment:

permissions:
  contents: read

jobs:
  job_detail:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{github.event.pull_request.url}}
        echo ${{github.event.pull_request.comments_url }}
        echo ${{github.event.comment.body }}
        echo ${{github.event.comment.issue_url }}
        echo ${{github.event.comment.html_url }}
        echo ${{ github.event.issue.pull_request.url }}
        echo ${{github.event_name}}
        echo ${{github.ref}}
        echo ${{github.ref_name}}
        echo ${{github.sha}}
        echo ${{github.head_ref}}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Lint with flake8
      run: |
        tox -e cilinter
    - name: Test with pytest
      run: |
        tox
