# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    tags:       
      - v1.*
  issue_comment:

permissions:
  pull-requests: read
  repository-projects: read

jobs:
  job_detail:
    runs-on: ubuntu-latest
    outputs:
      BRANCH: ${{steps.load-pr.outputs.branch }}
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - id: load-pr
      run: |
        echo ${{github.event.pull_request.url}}
        echo ${{github.event.pull_request.comments_url }}
        echo ${{github.event.comment.body }}
        echo ${{github.event.comment.issue_url }}
        echo ${{github.event.comment.html_url }}
        echo ${{ github.event.issue.pull_request.url }}
        
        response=$(curl -sSf --url ${{ github.event.issue.pull_request.url }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'  --header 'content-type: application/json')
        branch=$(python3 -c "import sys, json; print(json.load(sys.stdin)['head']['ref'])" <<< "$response")
        echo "::set-output name=branch::$branch"
  build:

    runs-on: ubuntu-latest
    needs: job_detail
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ needs.job_detail.outputs.BRANCH }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Lint with flake8
      run: |
        tox -e cilinter
    - name: Test with pytest
      run: |
        tox
