# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
  push:
    tags:       
      - v1.*
  issue_comment:

# permissions:
#   pull-requests: read
#   contents: read
jobs:
  pr_details:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'publish version=')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Get value from comment
        id: extract_pr_details
        run: |
          response=$(curl -sSf --url ${{ github.event.issue.pull_request.url }} --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'  --header 'content-type: application/json')
          branch=$(python3 -c "import sys, json; print(json.load(sys.stdin)['head']['ref'])" <<< "$response")
          echo "branch=$branch" >> $GITHUB_OUTPUT
          echo "latest_version=$(echo ${{ github.event.comment.body }} | grep -o "version=*.*.*" | cut -d "=" -f 2)" >> "GITHUB_OUTPUT"
    outputs:
      latest_version: ${{ steps.extract_pr_details.outputs.latest_version }}
      branch: ${{ steps.extract_pr_details.outputs.branch }}
        

  nextjob:
    runs-on: ubuntu-latest
    needs: pr_details
    steps:
      - name: Print pr details for ${{ needs.pr_details.outputs.branch}}
        run: |
           echo "Current pr branch : ${{ needs.pr_details.outputs.branch}}"
           echo "Current version : ${{ needs.pr_details.outputs.latest_version}}"
        
      
        
