# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
  push:
    tags:       
      - v1.*
  issue_comment:

permissions:
  pull-requests: read
  contents: read
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id:  extract_version
        name: Extract version from ${{  github.ref_name }}
        run: |
            version=$(echo "${{ github.ref_name }}" | cut -d 'v' -f 2)
            echo "version=$version" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.extract_version.outputs.version }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Running job 2 ${{ needs.job1.outputs.version }}
        id: job1_step
        run: |
          echo "=needs.job1.outputs.version ==> ${{ needs.job1.outputs.version }}"
          echo "version1=${{ needs.job1.outputs.version }}" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.job1_step.outputs.version1 }}